# Configuration for Duplicate Issues Detection
# This configuration enables automatic detection and commenting on potential duplicate issues

# Enable duplicate detection
enabled: true

# Detection settings
detection:
  # Minimum similarity threshold (0.0 to 1.0, where 1.0 is identical)
  # 0.7 means 70% similarity is required to consider it a potential duplicate
  similarity_threshold: 0.7
  
  # Fields to compare when detecting duplicates
  compare_fields:
    - title      # Issue title
    - body       # Issue description/body
    - labels     # Issue labels (optional)
  
  # Number of recent issues to search through (helps with performance)
  # Set to 0 to search all open issues
  search_limit: 100
  
  # Only check issues that are currently open
  only_open_issues: true

# Comment settings
comments:
  # Enable commenting on potential duplicates
  enabled: true
  
  # Comment when duplicate is detected
  duplicate_comment: |
    👋 @{{ issue.user.login }}
    
    Thanks for opening this issue! I've detected that this might be similar to existing issues:
    
    {% for duplicate in duplicates %}
    - [{{ duplicate.title }}]({{ duplicate.html_url }}) (#{{ duplicate.number }})
    {% endfor %}
    
    Please check if any of these existing issues address your concern. If this is indeed a duplicate, consider adding your specific details or use case to the existing issue instead.
    
    If you believe this is **not** a duplicate, please add more details to help differentiate it from the existing issues.
    
    *This comment was automatically generated by the Duplicate Issues detection app.*
  
  # Option to add labels to potential duplicates
  add_label: "possible-duplicate"

# Exclusions
exclude:
  # Don't check issues with these labels
  labels:
    - "not-duplicate"
    - "confirmed-unique"
    - "enhancement"
  
  # Don't check issues from these users (useful for bots, maintainers)
  users: []
  
  # Don't check issues with these titles (regex patterns)
  title_patterns: []

# Performance settings
performance:
  # Maximum number of duplicates to show in a single comment
  max_duplicates_shown: 5
  
  # Minimum issue body length to perform detection (avoid very short issues)
  min_body_length: 20

# Behavior settings
behavior:
  # Whether to check issues immediately when opened
  check_on_open: true
  
  # Whether to recheck when issue is edited
  check_on_edit: false
  
  # Whether to remove duplicate label/comment if issue is edited and no longer similar
  auto_remove_on_edit: true