# .github/.github/FUNDING.yml

github: [devinschumacher]
liberapay: devinschumacher
open_collective: devinschumacher

custom: [
"https://serp.co",
"https://serp.ai",
"https://devinschumacher.com",
"https://serpdownloaders.github.io",
]


# patreon: devinschumacher
# ko_fi: devinschumacher
# buy_me_a_coffee: devinschumacher
# thanks_dev: devinschumacher
