github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co",
"https://serp.co",
"https://devinschumacher.com",
"https://addons.mozilla.org/en-US/firefox/user/19256633/"
]
