# .github/.github/FUNDING.yml

github: [devinschumacher, mdsbest,templatethemes,professor-serp,mrserpdownloader,serpgamedeveloper,serp-y,mrmerchantaccountman]

custom: ["https://github.com/devinschumacher", "https://github.com/mdsbest", "https://github.com/templatethemes"]


# patreon: devinschumacher
# open_collective: devinschumacher
# ko_fi: devinschumacher
# liberapay: devinschumacher
# buy_me_a_coffee: devinschumacher
# thanks_dev: devinschumacher
