# These are supported funding model platforms

github: [devinschumacher]
patreon: devinschumacher
open_collective: devinschumacher
ko_fi: devinschumacher
liberapay: devinschumacher
buy_me_a_coffee: devinschumacher
thanks_dev: devinschumacher
