# .github/.github/FUNDING.yml

github: [devinschumacher]

custom: [
"https://github.com/mdsbest", 
"https://github.com/templatethemes",
"https://github.com/professor-serp",
"https://github.com/mrserpdownloader",
"https://github.com/serpgamedeveloper",
"https://github.com/serp-y",
"https://github.com/mrmerchantaccountman",
]


# patreon: devinschumacher
# open_collective: devinschumacher
# ko_fi: devinschumacher
# liberapay: devinschumacher
# buy_me_a_coffee: devinschumacher
# thanks_dev: devinschumacher
