name: "Bug Report 🐛"
description: "Report a bug"
labels: ["bug"]
projects: ["serpapps/1"]
type: Bug

body:
  - type: markdown
    attributes:
      value: |
        ### 1. [Star the repo ⭐](https://raw.githubusercontent.com/serpapps/.github/refs/heads/main/images/star-repo.gif)
  
  - type: checkboxes
    id: faq-check
    attributes:
      label: FAQs
      options:
        - label: I have checked the FAQs (https://github.com/orgs/serpapps/discussions/categories/faq) for an existing solution before submitting this as a bug.
          required: true
    
  - type: dropdown
    id: os
    attributes:
      label: What OS (Operating System) are you using?
      options:
        - Mac
        - Windows
        - Linux
    validations:
      required: true
      
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Arc
        - Internet Explorer
        - Other
    validations:
      required: true
      
  - type: input
    id: webpage
    attributes:
      label: What URL (webpage) are you trying to download from?
      placeholder: https://somewebsite.com/blog/a-post-with-a-cool-video
    validations:
      required: true
      
  - type: input
    id: video
    attributes:
      label: What is the URL of the video you are trying to download?
      placeholder: https://www.loom.com/share/b19b38d0ce2b44f5a049b871d9a38925
    validations:
      required: true
        
  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: |
        Please paste the error message you are receiving
    validations:
      required: true
