name: "Bug Report 🐛 (Downloaders)"
description: "Report a bug for a downloader application"
labels: ["bug"]
projects: ["serpapps/1"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        ### 1. [Star the repo ⭐](https://raw.githubusercontent.com/serpapps/.github/refs/heads/main/images/star-repo.gif)
        |
        
  - type: markdown
    attributes:
      value: |
        ### 2. Check the [FAQs](https://github.com/orgs/serpapps/discussions/categories/faq) before submitting a bug
        |
        
  - type: dropdown
    id: os
    attributes:
      label: What OS (Operating System) are you using?
      options:
        - Mac
        - Windows
        - Linux
    validations:
      required: true
      
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Arc
        - Internet Explorer
        - Other
    validations:
      required: true
      
  - type: input
    id: webpage
    attributes:
      label: What URL (webpage) are you trying to download from?
      placeholder: https://somewebsite.com/blog/post-1234567890
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: "What app/extension version are you using? This is how you find out: https://github.com/serpapps/.github/discussions/6"
    validations:
      required: true
      
  - type: input
    id: video
    attributes:
      label: What is the URL of the video you are trying to download?
      placeholder: https://www.loom.com/share/b19b38d0ce2b44f5a049b871d9a38925
    validations:
      required: true
        
  - type: textarea
    id: message
    attributes:
      label: Message
      description: |
        You message
    validations:
      required: true
