name: "Bugs"
description: "Report a bug"
labels: "bug"
projects: "serpapps/1"
type: Bug

body:
  - type: markdown
    attributes:
      value: |
        ## Prerequisites
        Before submitting a bug report, please check our [FAQs](https://github.com/orgs/serpapps/discussions/categories/faq) for existing solutions.
  
  - type: checkboxes
    id: faq-check
    attributes:
      label: Confirmation
      options:
        - label: I have checked the FAQs for an existing solution before submitting this as a bug.
          required: true
    
  - type: dropdown
    id: os
    attributes:
      label: What OS (Operating System) are you using?
      options:
        - Mac
        - Windows
        - Linux
    validations:
      required: true
      
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Arc
        - Internet Explorer
        - Other
    validations:
      required: true
        
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Please explain the issue you're having. 
        The more details you give, the easier it is for us to fix it.
    validations:
      required: true
